# Generated by Django 5.2.17 on 2026-09-27 21:27

import apps.contas.models
import apps.contas.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='nome completo')),
                ('cpf', models.CharField(help_text='Somente digitos.', max_length=11, unique=True, validators=[apps.contas.validators.validar_cpf], verbose_name='CPF')),
                ('data_nascimento', models.DateField(validators=[apps.contas.validators.validar_maioridade], verbose_name='data de nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('chave_pix', models.CharField(blank=True, max_length=140, verbose_name='chave PIX')),
                ('tipo_chave_pix', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('EMAIL', 'E-mail'), ('PHONE', 'Telefone'), ('EVP', 'Chave aleatoria')], max_length=10, verbose_name='tipo da chave PIX')),
                ('email_verificado', models.BooleanField(default=False, verbose_name='e-mail verificado')),
                ('status_kyc', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em analise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=12, verbose_name='status do KYC')),
                ('kyc_atualizado_em', models.DateTimeField(blank=True, null=True, verbose_name='KYC atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-criado_em'],
            },
            managers=[
                ('objects', apps.contas.models.UsuarioManager()),
            ],
        ),
    ]
