# Generated by Django 5.2.17 on 2026-09-27 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='e-mail verificado em'),
        ),
        migrations.CreateModel(
            name='EnvioVerificacaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_verificacao_email', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'envio de verificacao de e-mail',
                'verbose_name_plural': 'envios de verificacao de e-mail',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', '-criado_em'], name='contas_envio_verif_idx')],
            },
        ),
    ]
